id: P009283
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22010
  title: བོད་ཀྱི་ཡི་གེའི་སྤྱི་རྣམ་བློ་གསལ་འཇུག་ངོགས
  author: ''
  volumes:
    3284bf1d16e64ff0b34b98faac8079f8:
      image_group_id: I5776
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
